# Generated by Django 4.2.1 on 2023-05-30 15:03

import apps.portfolio.models
import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Description')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('icon', models.FileField(blank=True, null=True, upload_to=apps.portfolio.models.rename_file, verbose_name='Icon')),
                ('sort_order', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Sort')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adress Email')),
                ('subject', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subject')),
                ('message', models.TextField(max_length=10000, verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('niveau', models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé')], max_length=60, verbose_name='Niveau')),
                ('technology', models.CharField(max_length=500, verbose_name='Technologie')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=apps.portfolio.models.rename_img)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=20)),
                ('published_date', models.DateTimeField(default=datetime.datetime(2023, 5, 30, 15, 3, 57, 418218, tzinfo=datetime.timezone.utc), verbose_name='Date de Publication')),
                ('favorites', models.BooleanField(default=False)),
                ('number_views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Views')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
